name: Shared build workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build-platform-linux:
    uses: ./.github/workflows/shared-build-linux.yml
    with:
      environment: ${{inputs.environment}}

  build-platform-windows:
    uses: ./.github/workflows/shared-build-windows.yml
    with:
      environment: ${{inputs.environment}}
